### PR TITLE
Add list of geometry types.

### PR DESCRIPTION
**Pull request by kubaszostak**

### CODE REVIEW

**Comment by pramsey** [comment]
I don't feel like this enhances the learning at all, it's just a big reference table.

**Comment by kubaszostak** [comment]
I agree. This table shouldn't appear in learning workshop. I just missing a full list of geometry types supported by PostGIS. When I started with PostGIS I wasn't sure if there are only Points, Lines and Polygons? Now I know that there are also things like CircularStringZM :-) I would be great to let others know that.

For beginners like me it's hard do figure out that for the same point geometry (ZM) there is so many different names :
- `PointZM` when creating new table *CREATE TABLE point_zm (ID serial, geom geometry(PointZM,2180));*
- `POINT` with dimension `4` when listing created above table in *geometry_columns* metadata
- `ST_Point` when checking geometry type using  ST_GeometryType()

**Comment by pramsey** [comment]
Maybe a section in a reference manual, or a smaller hands-on exploration of the topic in the workshop, rather than the table? I mean, the patterns are repetitive, it's not really necessary to itemize them all in the workshop.

**Comment by kubaszostak** [comment]
That's right. A reference manual is much better place for such kind of information.

**Pull request closed without merging**
